os: linux
node_js: '7'
sudo: required
env: DISPLAY=':99.0'
dist: trusty
language: ruby
rvm:
  - 2.4.0
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
 
before_script:
  - sh -e /etc/init.d/xvfb start